### ISSUE TITLE
Design for the Github CI status

### ISSUE THREAD

**Issue by sladyn98** [sladyn98/hawk-eye#8]
So the main aim of the application is to report the Github Actions CI Status. Points to consider while designing this: 

1. How do we want to track which CI Status to report  : The Github Status API  returns a [set of CI Statuses](https://developer.github.com/v3/repos/statuses/) do we want to report each and every CI check eg : hawk-eye octaocat status

2. Report Combined Failure: The Github Status API also provides us with [Combined Status] (https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref) for a particular commit SHA.

3. Which branch to track: Would we want to support multi-branch tracking or consider it as a future milestone to accomplish
                        
Currently hawk-eye creates a github token on login, so the API calls will be made using that token.

**Comment by sladyn98** [comment]
CC: @derhuerst

**Comment by derhuerst** [comment]
for reference purposes: open-source-ideas/open-source-ideas#224

---

> How do we want to track which CI Status to report : The Github Status API returns a set of CI Statuses do we want to report each and every CI check eg : `hawk-eye octaocat status`

From my gut feeling, I'd say that by default it should show *all* statuses, but provide a way to filter by `status.creator.login`, and later optionally by platform-specific filters (e.g. for different jobs per CI environment).

> Report Combined Failure: The Github Status API also provides us with [Combined Status](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref) for a particular commit SHA.

We could use this for `hawk-eye`'s exit code. This allows GitHub to do the business logic about wether the commit has been checked successfully (keep in mind that this logic might become more complex eventually).

> Which branch to track: Would we want to support multi-branch tracking or consider it as a future milestone to accomplish

I would mimic the behaviour of [`travis-watch`](https://github.com/juliangruber/travis-watch) here: Fetch the statuses of the `HEAD` git commit, and fail if we can't find any statuses for it.

Keep in mind that this is my personal subjective opinion, based on my personal dev workflow.

**Comment by derhuerst** [comment]
Some general feedback about `hawk-eye`:

From browsing the WIP source code, I like the clear separation of *configuring* `hawk-eye` vs *running* it:

- *Configuring* requires human input anyways. It might become a lot more complex in the future, with more supported platforms & options.
- *Running* does not require human input. It should be scriptable. Its API shouldn't break.

> Enable commands to get the CI status from Github Actions. eg: `hawk-eye getCIStatus` [...].

*Running* seems to be the *default use case*, so I'd make it as accessibly as possible: just `hawk-eye`. All other features would live in sub-commands, e.g. `hawk-eye configure`.

Other comments:

- Why is the default config file in `~/.cobra.yml`? Doesn't that clash with other tools using `spf13/cobra`? Also, for the location of the config file, I'd prefer `~/.config` *a lot* over `~` (see e.g. the [npm lib for this](https://github.com/sindresorhus/env-paths/blob/6eb0a4a3a2c0e34ba6b80513ec6676df2367c402/readme.md#usage)).
